[build]
command = "bash ./netlify-build.sh"
publish = "build/web"
[build.environment]
FLUTTER_VERSION = "3.27.2"
SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
from = "/manual/*"
to = "/web_static_files/manual/:splat"
status = 200
